<?php

	$lunes = array("primera" => array("Nombre" => "Sistemas de control de versiones distribuidas - Controla las versiones de tu trabajo con GIT", 
						"Ponente" => "José Ignacio Álvarez Ruiz - @neonigmacdb", 
						"Empresa" => "Redsys - @Redsys_es",
						"Imagen" => "img/jose_ignacio_alvarez_ruiz.jpg",
						"Hora" => "8:30 - 9:45"),
					"segunda" => array("Nombre" => "Servicios web con Python + web.py", 
						"Ponente" => "José Ignacio Álvarez Ruiz - @neonigmacdb", 
						"Empresa" => "Redsys - @Redsys_es",
						"Imagen" => "img/jose_ignacio_alvarez_ruiz.jpg",
						"Hora" => "9:45 - 10:45"),
					"tercera" =>array("Nombre" => "WooCommerce: crea tu propia tienda online", 
						"Ponente" => "Fco. Javier Carazo Gil - @fjcarazo", 
						"Empresa" => "Codection - @codection",
						"Imagen" => "img/Fco_Javier.jpg",
						"Hora" => "11:45 - 12:45"),
					"cuarta" =>array("Nombre" => "Envenenamiento DNS", 
						"Ponente" => "Rafael Delgado - @rafadelgado89", 
						"Empresa" => "Alumno 1º DAW",
						"Imagen" => "img/Rafael_Delgado.jpg",
						"Hora" => "12:20 - 13:20"),
					"quinta" =>array("Nombre" => "Introducción Angular 5 y Angular Material", 
						"Ponente" => "Rafael Mellado - @RafaMelladoJim y Daniel Gestino - @DaniGestino", 
						"Empresa" => "Alumnos 2º DAW",
						"Imagen" => "img/Rafa_Mellado.jpg",
						"Hora" => "12:20 - 13:20"),
					"sexta" =>array("Nombre" => "Tweepy. Cuando Python escucha lo que dice un pajarito", 
						"Ponente" => "Nieves Borrero - @nievesborrero y Pablo León - @PabloLeonPsi", 
						"Empresa" => "Alumnos 2º DAW",
						"Imagen" => "img/Nieves_Borrero_y_Pablo_Leon.jpg",
						"Hora" => "13:30 - 14:15"));
	$martes = array("primera" => array("Nombre" => "Geolocalización de usuarios sin GPS", 
						"Ponente" => "Eduardo Sánchez Toril - @eduSatoe", 
						"Empresa" => "IES Fidiana",
						"Imagen" => "img/Edu_Sanchez.jpg",
						"Hora" => "9:00 - 10:00"),
					"segunda" => array("Nombre" => "Introducción al análisis de binarios", 
						"Ponente" => "Miguel Ángel Arroyo - @Miguel_Arroyo76", 
						"Empresa" => "SVT Cloud",
						"Imagen" => "img/Miguel_Angel_Arroyo.jpg",
						"Hora" => "10:00 - 11:30"),
					"tercera" => array("Nombre" => "Digital MKG: herramientas para analizar webs - @dobussmkt", 
						"Ponente" => "JL García-Morato y José Huertas", 
						"Empresa" => "Dobuss",
						"Imagen" => "img/dobuss.jpg",
						"Hora" => "12:00 - 13:00"),
					"cuarta" => array("Nombre" => "Deep-Learning", 
						"Ponente" => "Nicolás García Pedrajas - @NGPedrajas", 
						"Empresa" => "Universidad de Cordoba",
						"Imagen" => "img/Nicolas_Garcia.jpg",
						"Hora" => "13:00 - 14:30"));
	$miercoles =  array("primera" => array("Nombre" => "Design IS + workshop Diseño con Illustrator (Iniciación)", 
						"Ponente" => "Claudia López Iglesias", 
						"Empresa" => "WUL4 - @Wul4Info",
						"Imagen" => "img/Claudia_Lopez.jpg",
						"Hora" => "8:30 - 10:30"),
					"segunda" => array("Nombre" => "Cloud computing y AWS", 
						"Ponente" => "Javier Jiménez", 
						"Empresa" => "GrayHats",
						"Imagen" => "img/GrayHats.png",
						"Hora" => "8:30 - 9:00"),
					"tercera" => array("Nombre" => "CTF", 
						"Ponente" => "Rafa Sojo - @RaSr98", 
						"Empresa" => "Alumno 1º DAW",
						"Imagen" => "img/Rafa_Sojo.jpg",
						"Hora" => "9:00 - 11:00"),
					"cuarta" => array("Nombre" => "Web scraping like a ninja", 
						"Ponente" => "Rafa Sojo - @RaSr98", 
						"Empresa" => "Alumno 1º DAW",
						"Imagen" => "img/Rafa_Sojo.jpg",
						"Hora" => "11:00 - 11:30"),
					"quinta" => array("Nombre" => "Coworking", 
						"Ponente" => "Rafael Rodríguez", 
						"Empresa" => "LaZona",
						"Imagen" => "img/La_zona.png",
						"Hora" => "12:00 - 12:30"),
					"sexta" => array("Nombre" => "ChatBots", 
						"Ponente" => "Javier Aguirre - @javaguirre", 
						"Empresa" => "Reply.ai",
						"Imagen" => "img/Javier_Aguirre.jpg",
						"Hora" => "12:30 - 13:30"),
					"septima" => array("Nombre" => "Taller sobre Bots 102", 
						"Ponente" => "Cristina Santamaria - @crissantamarina", 
						"Empresa" => "Tnpgram - @tnpgram",
						"Imagen" => "img/Cristina_Santamarina.jpg",
						"Hora" => "13:30 - 14:30"));
	$jueves = array("primera" => array("Nombre" => "Cómo construir un modelo predictivo con Machine Learning", 
						"Ponente" => "Raúl Valentín - @ValentinRaul", 
						"Empresa" => "San Juan de Dios - @SanJuandeDios_",
						"Imagen" => "img/Raul_Valentin.jpg",
						"Hora" => "8:30 - 9:20"),
					"segunda" => array("Nombre" => "Producción de Realidad Virtual", 
						"Ponente" => "Manuel Jiménez - @manolitotic", 
						"Empresa" => "Cepcordoba - @cepcordoba",
						"Imagen" => "img/Manuel_Jimenez.jpg",
						"Hora" => "9:20 - 11:20"),
					"tercera" => array("Nombre" => "Cloud y contenerización con Docker", 
						"Ponente" => "Rafael Gómez", 
						"Empresa" => "Innovation Group",
						"Imagen" => "img/Innovation_Group.png",
						"Hora" => "12:00 - 13:00"),
					"cuarta" => array("Nombre" => "Crea tu propia nube", 
						"Ponente" => "Cristina Triviño - @cristinaetrivi / Pepe Molinero - @pepe_molinero98", 
						"Empresa" => "Alumnos 2º ASIR",
						"Imagen" => "img/Cristina_Triviño.jpg",
						"Hora" => "13:00 - 14:00"),
					"quinta" => array("Nombre" => "Testing en el marco de trabajo Scrum", 
						"Ponente" => "Alvaro Mesa , Raul Zarza y Antonio Arteche", 
						"Empresa" => "Innovation Group",
						"Imagen" => "img/Innovation_Group.png",
						"Hora" => "13:00 - 14:00"));
	$viernes = array("primera" => array("Nombre" => "Criptomonedas y altcoin", 
						"Ponente" => "David Fernández Gómez, Antonio David Ventura Serrano y Francisco Llamas Nuflo", 
						"Empresa" => "Alumnos 1º ASIR",
						"Imagen" => "img/David_Fernandez.jpg",
						"Hora" => "8:15 - 9:15"),
					"segunda" => array("Nombre" => "Iniciación al desarrollo de servicios REST", 
						"Ponente" => "Juan Antonio Romero", 
						"Empresa" => "ExAlumno DAW",
						"Imagen" => "img/Juan_Antonio_Romero.jpg",
						"Hora" => "8:15 - 9:15"),
					"tercera" => array("Nombre" => "Más allá de Agile", 
						"Ponente" => "Fernando Hidalgo - @hidabe", 
						"Empresa" => "Sopinet",
						"Imagen" => "img/Fernando_Hidalgo.jpg",
						"Hora" => "9:15 - 10:00"),
					"cuarta" => array("Nombre" => "¿Igualdad de género en el mundo tecnológico? Brecha digital", 
						"Ponente" => "Ana María Cuenca - @anmce_ / María Moreno - @mariamm6199 / Nieves Borrero - @nievesborrero / Soledad Cruz - @Solee_027", 
						"Empresa" => "Alumnas ASIR y DAW",
						"Imagen" => "img/Brecha_digital.jpg",
						"Hora" => "10:00 - 10:45"),
					"quinta" => array("Nombre" => "II Concurso Twitter Sysmana. Entrega de premios", 
						"Ponente" => " Profesorado", 
						"Empresa" => "IES Gran Capitan",
						"Imagen" => "img/cartelSysmana.jpg",
						"Hora" => "10:45 - 11:15"),
					"sexta" => array("Nombre" => "Clausura (Delegado Educación)", 
						"Ponente" => "Antonio López", 
						"Empresa" => "Delegado de Educación",
						"Imagen" => "img/Consejeria_educacion.jpg",
						"Hora" => "11:45 - 12:15"),
					"septima" => array("Nombre" => "Realidad Aumentada con WebGL", 
						"Ponente" => "Álvaro Serrano - @hb_asg", 
						"Empresa" => "Freelance",
						"Imagen" => "img/Alvaro_Serrano.jpg",
						"Hora" => "12:15 - 14:15"),
					"octava" => array("Nombre" => "¿Soy vulnerable?", 
						"Ponente" => "Lucia Expósito - @LuciaExpositoOr", 
						"Empresa" => "SvtCloud - @SVTCLOUD",
						"Imagen" => "img/Lucia_Exposito.jpg",
						"Hora" => "12:15 - 12:45"),
					"novena" => array("Nombre" => "Horus is coming... o casi", 
						"Ponente" => "Manuel Hidalgo - @Manu_Orfeo", 
						"Empresa" => "SvtCloud - @SVTCLOUD",
						"Imagen" => "img/Manuel_Hidalgo.png",
						"Hora" => "12:45 - 14:15"));
	
	$ponentes = array(array("Ponente" => "José Ignacio Álvarez Ruiz - @neonigmacdb", 
						"Empresa" => "Redsys - @Redsys_es",
						"Imagen" => "img/jose_ignacio_alvarez_ruiz.jpg"),
					array("Ponente" => "Fco. Javier Carazo Gil - @fjcarazo", 
						"Empresa" => "Codection - @codection",
						"Imagen" => "img/Fco_Javier.jpg"),
					array("Ponente" => "Rafael Delgado - @rafadelgado89", 
						"Empresa" => "Alumno 1º DAW",
						"Imagen" => "img/Rafael_Delgado.jpg"),
					array("Ponente" => "Rafael Mellado - @RafaMelladoJim y Daniel Gestino - @DaniGestino", 
						"Empresa" => "Alumnos 2º DAW",
						"Imagen" => "img/Rafa_Mellado.jpg"),
					array("Ponente" => "Nieves Borrero - @nievesborrero y Pablo León - @PabloLeonPsi", 
						"Empresa" => "Alumnos 2º DAW",
						"Imagen" => "img/Nieves_Borrero_y_Pablo_Leon.jpg"),
					array("Ponente" => "Eduardo Sánchez Toril - @eduSatoe", 
						"Empresa" => "IES Fidiana",
						"Imagen" => "img/Edu_Sanchez.jpg"),
					array("Ponente" => "Miguel Ángel Arroyo - @Miguel_Arroyo76", 
						"Empresa" => "SVT Cloud",
						"Imagen" => "img/Miguel_Angel_Arroyo.jpg"),
					array("Ponente" => "JL García-Morato y José Huertas", 
						"Empresa" => "Dobuss",
						"Imagen" => "img/dobuss.jpg"),
					array("Ponente" => "Nicolás García Pedrajas - @NGPedrajas", 
						"Empresa" => "Universidad de Cordoba",
						"Imagen" => "img/Nicolas_Garcia.jpg"),
					array("Ponente" => "Claudia López Iglesias", 
						"Empresa" => "WUL4 - @Wul4Info",
						"Imagen" => "img/Claudia_Lopez.jpg"),
					array("Ponente" => "Javier Jiménez", 
						"Empresa" => "GrayHats",
						"Imagen" => "img/GrayHats.png"),
					array("Ponente" => "Rafa Sojo - @RaSr98", 
						"Empresa" => "Alumno 1º DAW",
						"Imagen" => "img/Rafa_Sojo.jpg"),
					array("Ponente" => "Rafael Rodríguez", 
						"Empresa" => "LaZona",
						"Imagen" => "img/La_zona.png"),
					array("Ponente" => "Javier Aguirre - @javaguirre", 
						"Empresa" => "Reply.ai",
						"Imagen" => "img/Javier_Aguirre.jpg"),
					array("Ponente" => "Cristina Santamaria - @crissantamarina", 
						"Empresa" => "Tnpgram - @tnpgram",
						"Imagen" => "img/Cristina_Santamarina.jpg"),
					array("Ponente" => "Raúl Valentín - @ValentinRaul", 
						"Empresa" => "San Juan de Dios - @SanJuandeDios_",
						"Imagen" => "img/Raul_Valentin.jpg"),
					array("Ponente" => "Manuel Jiménez - @manolitotic", 
						"Empresa" => "Cepcordoba - @cepcordoba",
						"Imagen" => "img/Manuel_Jimenez.jpg"),
					array("Ponente" => "Cristina Triviño - @cristinaetrivi / Pepe Molinero - @pepe_molinero98", 
						"Empresa" => "Alumnos 2º ASIR",
						"Imagen" => "img/Cristina_Triviño.jpg"),
					array("Ponente" => "Alvaro Mesa , Raul Zarza y Antonio Arteche", 
						"Empresa" => "Innovation Group",
						"Imagen" => "img/Innovation_Group.png"),
					array("Ponente" => "David Fernández Gómez, Antonio David Ventura Serrano y Francisco Llamas Nuflo", 
						"Empresa" => "Alumnos 1º ASIR",
						"Imagen" => "img/David_Fernandez.jpg"),
					array("Ponente" => "Juan Antonio Romero", 
						"Empresa" => "ExAlumno DAW",
						"Imagen" => "img/Juan_Antonio_Romero.jpg"),
					array("Ponente" => "Fernando Hidalgo - @hidabe", 
						"Empresa" => "Sopinet",
						"Imagen" => "img/Fernando_Hidalgo.jpg"),
					array("Ponente" => "Ana María Cuenca - @anmce_ / María Moreno - @mariamm6199 / Nieves Borrero - @nievesborrero / Soledad Cruz - @Solee_027", 
						"Empresa" => "Alumnas ASIR y DAW",
						"Imagen" => "img/Brecha_digital.jpg"),
					array("Ponente" => " Profesorado", 
						"Empresa" => "IES Gran Capitan",
						"Imagen" => "img/cartelSysmana.jpg"),
					array("Ponente" => "Antonio López", 
						"Empresa" => "Delegado de Educación",
						"Imagen" => "img/Consejeria_educacion.jpg"),
					array("Ponente" => "Álvaro Serrano - @hb_asg", 
						"Empresa" => "Freelance",
						"Imagen" => "img/Alvaro_Serrano.jpg"),
					array("Ponente" => "Lucia Expósito - @LuciaExpositoOr", 
						"Empresa" => "SvtCloud - @SVTCLOUD",
						"Imagen" => "img/Lucia_Exposito.jpg"),
					array("Ponente" => "Manuel Hidalgo - @Manu_Orfeo", 
						"Empresa" => "SvtCloud - @SVTCLOUD",
						"Imagen" => "img/Manuel_Hidalgo.png"));

	$login = array(array("Nombre" => "José Ignacio",
						"Apellidos" => "Álvarez Ruiz",
						"Empresa" => "Redsys",
						"Patrocinio" => true,
						"FechaDesde" => "29/01/2018",
						"FechaHasta" => "01/02/2018",
						"Observaciones" => "Prefiero esos días porque si no luego la lío en el trabajo.",
						"Usuario" => "usuario1",
						"Contraseña" => "Usuario1-"),
					array("Nombre" => "Miguel Ángel",
						"Apellidos" => "Arroyo Luque",
						"Empresa" => "SVT Cloud",
						"Patrocinio" => true,
						"FechaDesde" => "30/01/2018",
						"FechaHasta" => "02/02/2018",
						"Observaciones" => "Espero que me patrocinen.",
						"Usuario" => "usuario2",
						"Contraseña" => "Usuario2-"));

	$cartelesSysmana = array(array("cartel" => "img/sysmana2009.jpg",
									"nombre" => "Sysmana 2009"),
							array("cartel" => "img/sysmana2010.jpg",
									"nombre" => "Sysmana 2010"),
							array("cartel" => "img/sysmana2011.jpg",
									"nombre" => "Sysmana 2011"),
							array("cartel" => "img/sysmana2012.jpg",
									"nombre" => "Sysmana 2012"),
							array("cartel" => "img/sysmana2013.jpg",
									"nombre" => "Sysmana 2013"),
							array("cartel" => "img/sysmana2014.jpg",
									"nombre" => "Sysmana 2014"),
							array("cartel" => "img/sysmana2015.jpg",
									"nombre" => "Sysmana 2015"),
							array("cartel" => "img/sysmana2016.jpg",
									"nombre" => "Sysmana 2016"),
							array("cartel" => "img/sysmana2017.jpg",
									"nombre" => "Sysmana 2017"),
							array("cartel" => "img/cartelSysmanaGrande.jpg",
									"nombre" => "Sysmana 2018"));

	if(isset($_GET["dia"])){
		switch ($_GET["dia"]) {
			case 'Lunes':
				echo json_encode($lunes);
				break;
			case 'Martes':
				echo json_encode($martes);
				break;
			case 'Miercoles':
				echo json_encode($miercoles);
				break;
			case 'Jueves':
				echo json_encode($jueves);
				break;
			case 'Viernes':
				echo json_encode($viernes);
				break;
		}
	}

	if (isset($_GET["ponentes"])) {
		echo json_encode($ponentes);
	}

	if (isset($_GET["login"])) {
		echo json_encode($login);
	}

	if (isset($_GET["carteles"])) {
		echo json_encode($cartelesSysmana);
	}
?>